### ISSUE TITLE
Expose as a bower module

### ISSUE THREAD

**Issue by justinaray** [MyPureCloud/client-app-sdk#4]
- Add bower.json
- Discuss git submodule vs manual vs automated
- Expose doc.md within bower package?

**Comment by kellcomnet2** [comment]
Since bower is deprecated, this should probably be moved to will not implement.

**Comment by justinaray** [comment]
Agreed @kellcomnet2.  This was a legacy ticket around for quite awhile.  The package is available via npm and cdn in umd and es6 modules for consumption in maximum environments.  Closing this 👍
