### ISSUE TITLE
Example of Lifecycle Not Showing Events

### ISSUE THREAD

**Issue by L-L-the-noob** [MyPureCloud/client-app-sdk#50]
Hi!

I have tried to use the lifecycle example on purecloud but it's not showing the events. I think there's a problem in the bootstrap listener, the added function includes a setTimeout function for emitting bootstrap event with a 500ms delay but I think it should be placed out of the listener or otherwise it will not trigger any event at all and makes the example pretty useless.

There's also another problem on the focus/blur listeners but I'm not sure if it has anything to do with the codes in the example. I've tried to switch to other pages within purecloud or switch to other apps, but nothing seem to trigger the blur event and it cannot be re-focused to trigger the focus listener.

Thank you!

**Comment by justinaray** [comment]
@L-L-the-noob ...  Have you added the hooks to your advanced application config?  I suspect this is the reason you're not seeing the events fire and not running your callbacks.  It was recently brought up to me, and I agree, that the SDK docs should do a better job indicating that the hooks need to be configured for the SDK lifecycle events to work properly.

https://developer.mypurecloud.com/api/client-apps/advanced.html

**Comment by L-L-the-noob** [comment]
Thank you for the reply! It finally solved my problem but it took me a while to realize what does it mean by putting those in app config. I thought it has something to do with the codes and you should add them into the ClientApp constructor. Turns out it has something to do with the configuration INSIDE the integration config, and you have to click on the "advanced" option on the menu to the left under the configuration tab to manually put the JSON config in it.

The document really needs to be more clear on that. :P
