### ISSUE TITLE
Alerting API: showToastPopup is not working

### ISSUE THREAD

**Issue by slavik-chapelskyi** [MyPureCloud/client-app-sdk#84]
In one of your integration, we are using `showToastPopup` method of `AlertingApi` to display notifications in PureCloud.
And suddenly it stopped working.
In our logs, there is an error message -> `Cannot read property 'postMsgToPc' of undefined`

I`ve tried to use an example from docs, but it also doesn't work:

- Create Custom Client App with the https://mypurecloud.github.io/client-app-sdk/toast.html url (as provided in [docs](https://developer.mypurecloud.com/api/client-apps/index.html)).
- Click Send toast 

**Expected**:
The toast notification is successfully displayed inside Pure Cloud.

**Actual** 
The notification is not displayed.

`purecloud-client-app-sdk` version -> `1.4.0`

**Comment by justinaray** [comment]
@slavik-chapelskyi   Thanks for issue report.

For testing with the gh-hosted example, can you make sure you're providing a pcEnvironment querystring param?  For instance, https://mypurecloud.github.io/client-app-sdk/toast.html?pcEnvironment={{pcEnvironment}}.  That is my guess as to why you're not seeing the toast message in that case.  The default environment is mypurecloud.com and needs to be configured if you're running in a different region.

As for your other js error, that is very strange.  Can you tell us a bit more about your environment?  Are you consuming the library from CDN or npm?  If you're using the npm package, are you using webpack or another bundler?  We're wondering if the library is getting corrupted somehow at build time.

**Comment by justinaray** [comment]
Another possibility is that maybe the function is being bound/invoked on a different context?  If it's not invoked on a ClientApp instance, the call would fail with the same type of error you're reporting.

```js
// This should work
const myApp = new ClientApp(...);
myClientApp.alerting.showToastPopup(...);

// Binding to a different context will not work
myClientApp.alerting.showToastPopup.call({}, ...);
```

**Comment by slavik-chapelskyi** [comment]
@justinaray Thank for quick respond.

That was my bad.
I've missed to add `pcEnvironment` in `https://mypurecloud.github.io/client-app-sdk/toast.html` and that`s why though that it doesn't work.

Your second comment help me to figure out the issue.
After last refactoring we had, it turned out that `myClientApp.alerting.showToastPopup` was called in different `react` component in a way that it context was not bound to ClientApp instance any more.

Sorry for bothering you with this.
Thank you again for helping with this.
Have a nice day :tada:
